# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build
        run: |
          go build -o build/ ./01-variables-and-types/
          go build -o build/ ./02-conditionals/
          go build -o build/ ./03-loops/
          go build -o build/ ./04-functions/
          go build -o build/ ./05-errors/
          go build -o build/ ./06-user-defined-types/
          go build -o build/ ./07-concurrency/
          go build -o build/ ./08-interfaces/
          go build -o build/ ./10-builtin-libraries/
          go build -o build/ ./11-file-io/
          go build -o build/ ./12-std-io/
